services:
  app:
    environment:
      - HOST_PORT
      - LISTEN_PORT
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest"
    ports:
      - "${DOCKER_FORWARD_PORT}:${DOCKER_LISTEN_PORT}"
    restart: unless-stopped

networks:
  default:
    name: "${DOCKER_NETWORK}"
    external: true
