services:
  webhook:
    image: "waxarsatia/webhook-handler:latest"
    ports:
      - "9999:80"
    restart: unless-stopped

networks:
  default:
    name: "gacha"
    external: true

extra_hosts:
  - "host.docker.internal:host-gateway"
